# Generated by Django 3.1.1 on 2020-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.CharField(max_length=20)),
                ('apartment_type', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('apartment_name', models.CharField(max_length=20)),
                ('capacity', models.CharField(max_length=20)),
                ('bathroom', models.CharField(max_length=20)),
                ('washroom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_number', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('department_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DormAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DromDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(max_length=20)),
                ('is_checkin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('enter_year', models.CharField(max_length=20)),
                ('tutor_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('department_number', models.CharField(max_length=20)),
            ],
        ),
    ]
