# Generated by Django 3.1.1 on 2020-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='DromDistribution',
            new_name='DormDistribution',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enter_year',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='in_year',
        ),
    ]
