# Generated by Django 3.1.1 on 2020-12-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0002_auto_20201211_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormdistribution',
            name='is_checkin',
        ),
    ]
