# Generated by Django 3.1.1 on 2020-12-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0003_remove_dormdistribution_is_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='name',
            new_name='emergency_name',
        ),
    ]
