# Generated by Django 3.1.1 on 2020-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0004_auto_20201211_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='capacity',
            field=models.IntegerField(max_length=20),
        ),
    ]
