# Generated by Django 3.1.1 on 2020-12-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0005_auto_20201211_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dormadmin',
            old_name='number',
            new_name='supervisor_number',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='number',
            new_name='tutor_number',
        ),
    ]
