# Generated by Django 3.1.1 on 2020-12-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0008_changedorm_enterdorm_quitdorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('supervisor_number', models.CharField(max_length=20)),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='changedorm',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
