# Generated by Django 3.1.1 on 2020-12-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0009_auto_20201212_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedorm',
            name='apartment_name',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AddField(
            model_name='enterdorm',
            name='apartment_name',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='enterdorm',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quitdorm',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
