# Generated by Django 3.1.1 on 2020-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0010_auto_20201212_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedorm',
            name='apartment_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enterdorm',
            name='apartment_name',
            field=models.CharField(max_length=20),
        ),
    ]
