# Generated by Django 3.1.1 on 2020-12-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0011_auto_20201212_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedorm',
            name='deal_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='enterdorm',
            name='deal_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quitdorm',
            name='deal_time',
            field=models.DateTimeField(null=True),
        ),
    ]
