# Generated by Django 3.1.1 on 2020-12-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0012_auto_20201212_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('apartment_name', models.CharField(max_length=20)),
                ('tutor_number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('deal_time', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
