# Generated by Django 3.1.1 on 2020-12-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0013_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='apartment_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='region',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='room_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
