# Generated by Django 3.1.1 on 2020-12-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0014_auto_20201212_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='student_name',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
