# Generated by Django 3.1.1 on 2020-12-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0015_approval_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='student_name',
            field=models.CharField(max_length=20),
        ),
    ]
