# Generated by Django 3.1.1 on 2020-12-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormsys', '0017_auto_20201212_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rest_num',
            field=models.IntegerField(default=4),
        ),
    ]
